version: 2
jobs:
  build:
    docker:
      - image: debian:squeeze
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Wheres the base 2..
      - run:
          name: Print the Current Time
          command: date
